import type { PartField, PartType } from "./catalog.js";
import { LED_COLORS, type ModulePin } from "./modules.js";

const ledColors = [...LED_COLORS];

function choiceField(
  key: string,
  label: string,
  options: string[],
  settings: Pick<PartField, "identity" | "electrical" | "required" | "unit"> = { identity: true, electrical: false },
): PartField {
  return { key, label, kind: "choice", options, ...settings };
}

function numberField(
  key: string,
  label: string,
  unit: string,
  settings: Pick<PartField, "identity" | "electrical" | "required" | "min" | "max"> = { identity: true, electrical: true, required: true },
): PartField {
  return { key, label, kind: "number", unit, ...settings };
}

function builtIn(
  id: string,
  name: string,
  category: PartType["category"],
  aliases: string[],
  photoHint: string,
  description: string,
  support: PartType["support"],
  fields: PartField[],
  mapping: PartType["mapping"],
  pinout?: ModulePin[],
): PartType {
  return {
    id,
    name,
    category,
    aliases,
    photoHint,
    description,
    fields,
    support,
    mapping,
    ...(pinout ? { pinout } : {}),
    builtIn: true,
  };
}

const switchPins: ModulePin[] = [
  { id: "1", name: "switch leg 1", etype: "passive" },
  { id: "2", name: "switch leg 2", etype: "passive" },
];
const moduleDigitalPins: ModulePin[] = [
  { id: "VCC", name: "VCC", etype: "power_in" },
  { id: "GND", name: "GND", etype: "power_in" },
  { id: "OUT", name: "digital OUT", etype: "output" },
];
const moduleAnalogPins: ModulePin[] = [
  { id: "VCC", name: "VCC", etype: "power_in" },
  { id: "GND", name: "GND", etype: "power_in" },
  { id: "AOUT", name: "analog OUT", etype: "output" },
];

/** The starter-kit catalog described in docs/ui-redesign-plan.md §5.2. */
export const BUILT_IN_PART_TYPES: PartType[] = [
  // Full support: library modules with electrical checks and simulation.
  builtIn(
    "led",
    "LED",
    "lights",
    ["led", "leds", "light emitting diode", "indicator light", "indicator led"],
    "A small two-leg, domed or flat-topped indicator lamp; the longer leg is usually the anode.",
    "A light-emitting diode; its color changes the forward-voltage range and it always needs a series resistor.",
    "full",
    [
      choiceField("color", "Color", ledColors, { identity: true, electrical: true, required: true }),
      choiceField("size", "Size", ["3", "5", "10"], { identity: false, electrical: false, required: false, unit: "mm" }),
    ],
    { kind: "module", module: "led", params: { color: "color" } },
  ),
  builtIn(
    "resistor",
    "Resistor",
    "resistors",
    ["resistor", "resistors", "res", "ohm resistor", "ohm resistors"],
    "A small axial cylinder with colored bands around its body and two wire leads.",
    "A two-lead current-limiting part; read its colored bands or printed value to find its resistance.",
    "full",
    [
      numberField("ohms", "Resistance", "Ω"),
      choiceField("bands", "Bands", ["4", "5"], { identity: false, electrical: false, required: false }),
    ],
    { kind: "module", module: "resistor", params: { ohms: "ohms" } },
  ),
  builtIn(
    "button",
    "Push button",
    "switches",
    ["button", "buttons", "push button", "pushbutton", "tactile switch", "tact switch"],
    "A small square tactile switch with four legs, usually spanning the breadboard center gap.",
    "A four-leg push button whose two pairs are joined until the button is pressed.",
    "full",
    [],
    { kind: "module", module: "button" },
  ),
  builtIn(
    "photoresistor",
    "Light sensor (LDR)",
    "sensors",
    ["light sensor", "light sensors", "ldr", "photoresistor", "photocell", "cds cell"],
    "A small round two-lead disk with a zig-zag or serpentine light-sensitive track on its face.",
    "A photoresistor whose resistance falls as the light gets brighter.",
    "full",
    [],
    { kind: "module", module: "photoresistor" },
  ),
  builtIn(
    "knob",
    "Knob (potentiometer)",
    "sensors",
    ["knob", "knobs", "pot", "pots", "potentiometer", "potentiometers", "rotary potentiometer"],
    "A three-pin component with a shaft or small adjustment screw and two outer terminals.",
    "A three-pin variable resistor; the middle wiper gives a voltage that follows the knob position.",
    "full",
    [numberField("ohms", "Resistance", "Ω")],
    { kind: "module", module: "potentiometer", params: { ohms: "ohms" } },
  ),
  builtIn(
    "buzzer-active",
    "Buzzer (active)",
    "sound",
    ["active buzzer", "active buzzers", "buzzer active", "beeper", "beepers"],
    "A round black sounder with a + mark or polarity marking and two leads.",
    "An active buzzer that beeps when powered; its oscillator is built in.",
    "full",
    [],
    { kind: "module", module: "buzzer-active" },
  ),
  builtIn(
    "buzzer-passive",
    "Buzzer (passive)",
    "sound",
    ["passive buzzer", "passive buzzers", "buzzer passive", "magnetic buzzer", "piezo buzzer"],
    "A round black two-lead sounder, often marked +, that needs an alternating drive signal.",
    "A passive buzzer that makes a tone only when the Arduino drives it with tone().",
    "full",
    [],
    { kind: "module", module: "buzzer-passive" },
  ),

  // Modelled support: use a full module while retaining the user's actual part name.
  builtIn(
    "trimmer-pot",
    "Trimmer potentiometer",
    "sensors",
    ["trimmer pot", "trimpot", "trim pot", "preset pot", "preset potentiometer", "103"],
    "A small square or rectangular blue, white, or green adjustment pot with a screw and three inline pins.",
    "A preset variable resistor that ViBread models as a rotary knob.",
    "modelled",
    [numberField("ohms", "Resistance", "Ω")],
    { kind: "modelled", module: "potentiometer", params: { ohms: "ohms" } },
  ),
  builtIn(
    "ntc-thermistor",
    "NTC thermistor",
    "sensors",
    ["thermistor", "thermistors", "ntc", "ntc thermistor", "temperature resistor"],
    "A small bead, disk, or epoxy-coated two-lead part, commonly black, blue, or bead-shaped.",
    "A temperature-dependent resistor that ViBread models as a light sensor for a first design.",
    "modelled",
    [],
    { kind: "modelled", module: "photoresistor" },
  ),
  builtIn(
    "force-sensor",
    "Force sensor (FSR)",
    "sensors",
    ["force sensor", "force sensors", "fsr", "force sensitive resistor", "force-sensitive resistor"],
    "A thin flat strip or round pad with a printed sensing area and two tail contacts.",
    "A force-sensitive resistor that ViBread models as a light sensor for a first design.",
    "modelled",
    [],
    { kind: "modelled", module: "photoresistor" },
  ),
  builtIn(
    "flex-sensor",
    "Flex sensor",
    "sensors",
    ["flex sensor", "flex sensors", "flex resistor", "bend sensor"],
    "A long thin flexible strip with a dark printed sensing track and two contacts at one end.",
    "A bend-sensitive resistor that ViBread models as a light sensor for a first design.",
    "modelled",
    [],
    { kind: "modelled", module: "photoresistor" },
  ),
  builtIn(
    "piezo-disc",
    "Piezo disc",
    "sound",
    ["piezo", "piezo disc", "piezo element", "piezo disk", "piezo transducer"],
    "A thin brass-colored round disk, often with a white ceramic center and two soldered wires.",
    "A piezoelectric disc that ViBread models as a passive buzzer.",
    "modelled",
    [],
    { kind: "modelled", module: "buzzer-passive" },
  ),

  // Basic support: generic pins and a conservative digital/analog role.
  builtIn(
    "tilt-switch",
    "Tilt switch",
    "switches",
    ["tilt switch", "tilt switches", "tilt sensor", "ball tilt switch"],
    "A small tube or capsule containing a loose metal ball, with two wire leads.",
    "A normally-open switch that closes when tilted in one direction.",
    "basic",
    [],
    { kind: "generic", role: "digital-sensor" },
    switchPins,
  ),
  builtIn(
    "reed-switch",
    "Reed switch",
    "switches",
    ["reed switch", "reed switches", "magnetic switch", "magnetic reed"],
    "A slender glass capsule with two metal leads and visible contacts inside.",
    "A magnetically actuated two-lead switch.",
    "basic",
    [],
    { kind: "generic", role: "digital-sensor" },
    switchPins,
  ),
  builtIn(
    "slide-switch",
    "Slide switch",
    "switches",
    ["slide switch", "slide switches", "sliding switch"],
    "A small rectangular switch with a short slider on top and two or three pins.",
    "A manually operated switch; ViBread uses its two-state digital behavior.",
    "basic",
    [],
    { kind: "generic", role: "digital-sensor" },
    switchPins,
  ),
  builtIn(
    "pir-module",
    "PIR motion module",
    "sensors",
    ["pir", "pir module", "pir motion module", "motion sensor", "motion detector"],
    "A small circuit board with a large white Fresnel dome and a three-pin header.",
    "A motion detector module with VCC, GND, and a digital output.",
    "basic",
    [],
    { kind: "generic", role: "digital-sensor" },
    moduleDigitalPins,
  ),
  builtIn(
    "sound-module",
    "Sound module (digital out)",
    "sensors",
    ["sound module", "sound sensor", "microphone module", "clap sensor", "sound modules"],
    "A small board with a microphone can, a trim screw, and a three-pin VCC/GND/OUT header.",
    "A sound-level module with a thresholded digital output.",
    "basic",
    [],
    { kind: "generic", role: "digital-sensor" },
    moduleDigitalPins,
  ),
  builtIn(
    "ir-obstacle-module",
    "IR obstacle module",
    "sensors",
    ["ir obstacle", "ir obstacle module", "infrared obstacle", "infrared obstacle module"],
    "A small board with paired clear/dark IR emitters, a trim screw, and a three-pin header.",
    "An infrared reflective obstacle sensor with a thresholded digital output.",
    "basic",
    [],
    { kind: "generic", role: "digital-sensor" },
    moduleDigitalPins,
  ),
  builtIn(
    "soil-moisture-module",
    "Soil-moisture module",
    "sensors",
    ["soil moisture", "soil-moisture module", "soil sensor", "moisture sensor"],
    "A probe or fork connected to a small board with a trim screw and VCC/GND/AOUT pins.",
    "A soil-moisture module with an analog voltage output.",
    "basic",
    [],
    { kind: "generic", role: "analog-sensor" },
    moduleAnalogPins,
  ),

  // List-only support: remember these parts but do not use them in generated designs.
  builtIn(
    "rgb-led",
    "RGB LED",
    "lights",
    ["rgb led", "rgb leds", "rgb light", "multicolor led"],
    "A two- or four-lead LED with a clear or diffused lens and three color dies.",
    "A multi-color LED kept in the inventory while ViBread's starter model supports single-color LEDs.",
    "list-only",
    [choiceField("color", "Dominant color", ledColors, { identity: true, electrical: true, required: false })],
    { kind: "note" },
  ),
  builtIn(
    "capacitor",
    "Capacitor",
    "passives",
    ["capacitor", "capacitors", "cap", "electrolytic capacitor", "ceramic capacitor"],
    "A small disk or cylindrical can with two leads; an electrolytic can has a stripe marking −.",
    "A charge-storage part, recorded by its capacitance but not yet used in generated designs.",
    "list-only",
    [numberField("capacitanceUf", "Capacitance", "µF", { identity: true, electrical: true, required: true, min: 0 })],
    { kind: "note" },
  ),
  builtIn(
    "diode",
    "Diode",
    "semiconductors",
    ["diode", "diodes", "rectifier diode", "signal diode", "schottky diode"],
    "A small black or glass axial cylinder with a contrasting stripe at the cathode end.",
    "A one-way semiconductor part kept in the inventory for future circuit support.",
    "list-only",
    [choiceField("kind", "Kind", ["signal", "rectifier", "Schottky"], { identity: true, electrical: true, required: false })],
    { kind: "note" },
  ),
  builtIn(
    "transistor",
    "Transistor",
    "semiconductors",
    ["transistor", "transistors", "npn transistor", "pnp transistor"],
    "A small three-legged black or flat package, often marked with a short part number.",
    "A three-terminal transistor recorded by polarity but not yet designed into circuits.",
    "list-only",
    [choiceField("polarity", "Polarity", ["NPN", "PNP"], { identity: true, electrical: true, required: false })],
    { kind: "note" },
  ),
  builtIn(
    "seven-segment",
    "7-segment display",
    "displays",
    ["7-segment display", "7 segment display", "seven segment", "seven-segment display"],
    "A rectangular black display with seven separate bar-shaped LED segments and several pins.",
    "A numeric display kept in the inventory for future display support.",
    "list-only",
    [],
    { kind: "note" },
  ),
  builtIn(
    "lcd-16x2",
    "LCD 16×2",
    "displays",
    ["lcd", "lcd 16x2", "lcd 16×2", "16x2 lcd", "character lcd"],
    "A green or blue rectangular character display on a board with a long pin header.",
    "A 16-column by 2-row character display kept for reference.",
    "list-only",
    [],
    { kind: "note" },
  ),
  builtIn(
    "74hc595",
    "74HC595",
    "semiconductors",
    ["74hc595", "74hc 595", "595 shift register", "shift register"],
    "A black DIP chip with 16 pins, often marked 74HC595.",
    "An 8-bit shift register kept in the inventory for future support.",
    "list-only",
    [],
    { kind: "note" },
  ),
  builtIn(
    "dht11",
    "DHT11",
    "sensors",
    ["dht11", "dht 11", "humidity sensor", "temperature humidity sensor"],
    "A blue vented rectangular sensor package, commonly on a small three-pin module.",
    "A temperature and humidity sensor kept in the inventory for future support.",
    "list-only",
    [],
    { kind: "note" },
  ),
  builtIn(
    "hc-sr04",
    "HC-SR04",
    "sensors",
    ["hc-sr04", "hc sr04", "ultrasonic sensor", "ultrasonic module"],
    "A board with two matching silver ultrasonic transducers like a pair of eyes.",
    "An ultrasonic distance module kept in the inventory for future support.",
    "list-only",
    [],
    { kind: "note" },
  ),
  builtIn(
    "ir-receiver",
    "IR receiver + remote",
    "modules",
    ["ir receiver", "infrared receiver", "ir remote", "infrared remote", "remote control"],
    "A small dark three-pin IR receiver, often stored beside a handheld button remote.",
    "An infrared receiver and remote pair kept in the inventory for future support.",
    "list-only",
    [],
    { kind: "note" },
  ),
  builtIn(
    "keypad",
    "Keypad",
    "modules",
    ["keypad", "matrix keypad", "4x4 keypad", "4×4 keypad", "4x3 keypad"],
    "A flat rectangular membrane or plastic keypad with a grid of numbered buttons and a ribbon tail.",
    "A button matrix kept in the inventory for future support.",
    "list-only",
    [choiceField("layout", "Layout", ["4x4", "4x3"], { identity: true, electrical: false, required: false })],
    { kind: "note" },
  ),
  builtIn(
    "joystick",
    "Joystick",
    "modules",
    ["joystick", "joysticks", "thumb joystick", "analog joystick"],
    "A small board with a spring-centered stick, often with a push switch and five pins.",
    "A two-axis joystick kept in the inventory for future support.",
    "list-only",
    [],
    { kind: "note" },
  ),
  builtIn(
    "servo",
    "Servo",
    "motors",
    ["servo", "servos", "servo motor", "sg90", "micro servo"],
    "A rectangular plastic motor case with a three-wire lead and a small output horn.",
    "A positional motor kept in the inventory; motors stay out of starter designs.",
    "list-only",
    [],
    { kind: "note" },
  ),
  builtIn(
    "dc-motor",
    "DC motor",
    "motors",
    ["dc motor", "dc motors", "motor", "motors", "hobby motor"],
    "A small cylindrical metal motor with two terminals and often a visible shaft.",
    "A two-wire motor kept in the inventory; motors stay out of starter designs.",
    "list-only",
    [],
    { kind: "note" },
  ),
  builtIn(
    "stepper-motor",
    "Stepper motor",
    "motors",
    ["stepper motor", "stepper motors", "stepper"],
    "A boxy motor with a protruding shaft and a multi-wire connector or bundle.",
    "A multi-coil motor kept in the inventory for future support.",
    "list-only",
    [],
    { kind: "note" },
  ),
  builtIn(
    "relay-module",
    "Relay module",
    "modules",
    ["relay", "relay module", "relay modules"],
    "A small board dominated by a rectangular relay block, screw terminals, and a pin header.",
    "An electrically controlled switch kept in the inventory for future support.",
    "list-only",
    [],
    { kind: "note" },
  ),
  builtIn(
    "battery-holder",
    "Battery holder",
    "supplies",
    ["battery holder", "battery holders", "battery pack", "cell holder"],
    "A plastic tray or clip with spring contacts for one or more cylindrical batteries.",
    "A battery holder kept in the inventory for reference; power design support is not enabled yet.",
    "list-only",
    [numberField("cells", "Cells", "", { identity: true, electrical: true, required: false, min: 1 })],
    { kind: "note" },
  ),

  // Board and supplies: settings are intentionally not circuit InventoryItems.
  builtIn(
    "arduino",
    "Arduino Uno R3 / Nano",
    "board",
    ["arduino", "arduino uno", "uno", "uno r3", "arduino nano", "nano"],
    "A blue Arduino board with a USB connector, black microcontroller, and rows of pin headers.",
    "The Arduino Uno R3 or Nano board used as the mission controller.",
    "supply",
    [choiceField("board", "Board", ["uno-r3", "nano"], { identity: true, electrical: true, required: true })],
    { kind: "setting", setting: "board" },
  ),
  builtIn(
    "breadboard",
    "Breadboard 400 / 830",
    "board",
    ["breadboard", "breadboards", "400 point breadboard", "830 point breadboard", "mini breadboard"],
    "A white solderless board with a center channel and rows of numbered tie points.",
    "A 400-point or 830-point solderless breadboard for assembly.",
    "supply",
    [choiceField("size", "Size", ["400", "830"], { identity: true, electrical: false, required: true })],
    { kind: "setting", setting: "breadboard" },
  ),
  builtIn(
    "jumper-wires",
    "Jumper wires",
    "supplies",
    ["jumper wires", "jumper wire", "dupont wires", "male male", "male female", "female female", "m-m", "m-f", "f-f"],
    "Loose thin hookup wires with colorful insulation and pin or socket ends.",
    "M-M, M-F, or F-F jumper wires used to connect the breadboard.",
    "supply",
    [choiceField("ends", "Ends", ["M-M", "M-F", "F-F"], { identity: true, electrical: false, required: false })],
    { kind: "setting", setting: "none" },
  ),
  builtIn(
    "usb-cable",
    "USB cable",
    "supplies",
    ["usb cable", "usb lead", "usb cord", "arduino cable"],
    "A USB data cable with a standard computer plug and a board-side USB plug.",
    "A USB cable for programming or powering the board; it is not a circuit part.",
    "supply",
    [],
    { kind: "setting", setting: "none" },
  ),
];
