import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { GOLDEN } from "@vibread/fixtures";
import { layoutBoard } from "@vibread/assembly/layout";
import { revisionHash } from "@vibread/core";
import { compileBenchFirmware } from "@vibread/firmware";
import { buildFaultDictionary, evaluateRun, planSelfTest } from "../src/index.js";

interface Row {
  design: string;
  fault: string;
  verdict: string;
  rank: number;
  top3: string;
  summary: string;
}

async function main(): Promise<void> {
  const rows: Row[] = [];
  for (const golden of GOLDEN) {
    const layout = layoutBoard(golden.circuit);
    const plan = planSelfTest(golden.circuit, revisionHash(golden.circuit));
    const compiled = await compileBenchFirmware(plan);
    if (!compiled.ok || compiled.hex === undefined) throw new Error(`${golden.key}: bench firmware compile failed: ${compiled.log}`);
    const dictionary = await buildFaultDictionary({ circuit: golden.circuit, layout, plan, hex: compiled.hex, maxFaults: 40 });
    for (const entry of dictionary.entries) {
      const result = await evaluateRun({
        circuit: golden.circuit,
        layout,
        plan,
        lines: entry.lines,
        answers: entry.answers,
        kind: "selftest",
        revision: 1,
        runId: `fault-table-${golden.key}-${entry.fault}`,
        faultDictionary: dictionary,
      });
      rows.push({
        design: golden.key,
        fault: entry.fault,
        verdict: result.verdict,
        rank: result.diagnosis.candidates.findIndex((candidate) => candidate.cause === entry.fault) + 1,
        top3: result.diagnosis.candidates.slice(0, 3).map((candidate) => candidate.cause).join(", "),
        summary: result.diagnosis.summary,
      });
    }
  }

  const caught = rows.filter((row) => row.verdict === "fail").length;
  const first = rows.filter((row) => row.rank === 1).length;
  const second = rows.filter((row) => row.rank === 2).length;
  const third = rows.filter((row) => row.rank === 3).length;
  const fourthOrLater = rows.filter((row) => row.rank > 3).length;
  const notRanked = rows.filter((row) => row.rank === 0).length;
  const totals = `Totals: ${rows.length} applicable faults; ${caught} fail, ${rows.length - caught} pass; true cause rank #1=${first}, #2=${second}, #3=${third}, #4+= ${fourthOrLater}, not ranked=${notRanked}.`;
  const markdown = [
    "# ViBread fault table",
    "",
    "Generated by `npm run fault-table` using each golden layout, compiled bench firmware, SimSession, LineDecoder, and the bench evaluator.",
    "",
    "| Design | Fault | Verdict | True rank | Top 3 | Houston summary |",
    "|---|---|---:|---:|---|---|",
    ...rows.map((row) => `| ${row.design} | ${row.fault} | ${row.verdict} | ${row.rank || "—"} | ${row.top3 || "—"} | ${row.summary.replaceAll("|", "\\|")} |`),
    "",
    totals,
    "",
  ].join("\n");
  const output = resolve(dirname(fileURLToPath(import.meta.url)), "../../../docs/fault-table.md");
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, markdown, "utf8");
  console.log(totals);
  console.log(`Wrote ${output}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
