import { GOLDEN } from "@vibread/fixtures";
import { createPipeline } from "@vibread/tools";
import { memoryStore } from "./testing.js";
const store = memoryStore();
const g = GOLDEN[0]!;
const m = await store.createMission({ title: "t", brief: g.brief, ownerId: "o", inventory: g.inventory, mode: "review" });
await store.createRevision(m.id, { circuit: g.circuit, suite: g.suite, author: { kind: "human", id: "o", channel: "web" } });
const t = performance.now();
const r = await createPipeline({ store }).evaluate(m.id, 1);
console.log("ms", Math.round(performance.now() - t));
for (const rep of r.reports) console.log(rep.console, rep.verdict, rep.summary, JSON.stringify(rep.findings.map(f => [f.severity, f.ruleId, f.title, f.detail?.slice(0, 300)])));
console.log(Object.keys(r.artifacts).join(" "));
console.log("steps", r.steps?.steps.length, "sim", r.sim?.scenarios.map(s => `${s.id}:${s.ok}`).join(" "));
