import { fileURLToPath } from "node:url";
import type { Circuit, InventoryItem, TestSuite } from "@vibread/core";
import { knobNightLight, knobNightLightBrief, knobNightLightInventory, knobNightLightSuite, knobNightLightSuiteYaml } from "./knob-night-light.js";
import { launchControl, launchControlBrief, launchControlInventory, launchControlSuite, launchControlSuiteYaml } from "./launch-control.js";
import { moonPhaseBrief, moonPhaseInventory, moonPhaseLamp, moonPhaseSuite, moonPhaseSuiteYaml } from "./moon-phase-lamp.js";

export * from "./knob-night-light.js";
export * from "./launch-control.js";
export * from "./moon-phase-lamp.js";

export interface GoldenDesign {
  key: "moon-phase-lamp" | "knob-night-light" | "launch-control";
  brief: string;
  inventory: InventoryItem[];
  circuit: Circuit;
  suite: TestSuite;
  suiteYaml: string;
  /** Pre-built Intel HEX for the Uno (fixtures/hex/<key>.uno.hex), regenerated by `npx tsx fixtures/scripts/build-hex.ts`. */
  hexFile: string;
}

const hex = (key: GoldenDesign["key"]) => fileURLToPath(new URL(`../hex/${key}.uno.hex`, import.meta.url));

export const GOLDEN: GoldenDesign[] = [
  { key: "moon-phase-lamp", brief: moonPhaseBrief, inventory: moonPhaseInventory, circuit: moonPhaseLamp, suite: moonPhaseSuite, suiteYaml: moonPhaseSuiteYaml, hexFile: hex("moon-phase-lamp") },
  { key: "knob-night-light", brief: knobNightLightBrief, inventory: knobNightLightInventory, circuit: knobNightLight, suite: knobNightLightSuite, suiteYaml: knobNightLightSuiteYaml, hexFile: hex("knob-night-light") },
  { key: "launch-control", brief: launchControlBrief, inventory: launchControlInventory, circuit: launchControl, suite: launchControlSuite, suiteYaml: launchControlSuiteYaml, hexFile: hex("launch-control") },
];
